# Generated by Django 3.2.10 on 2022-01-31 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('labelImage', models.ImageField(blank=True, null=True, upload_to='images/translators')),
                ('source_video', models.FileField(upload_to='videos/source', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mkv'])])),
                ('source_audio', models.FileField(blank=True, null=True, upload_to='audios/source', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['flv', 'FLV', 'wav'])])),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('translated_text', models.TextField(blank=True, null=True)),
                ('translated_audio', models.FileField(blank=True, null=True, upload_to='audios/destination', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['flv', 'FLV', 'wav'])])),
                ('translated_video_audio', models.FileField(blank=True, null=True, upload_to='videos/destination', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mkv'])])),
                ('source_language', models.CharField(choices=[('fr', 'French'), ('en', 'Emglish')], max_length=5)),
                ('destination_language', models.CharField(choices=[('fr', 'French'), ('en', 'Emglish')], max_length=5)),
            ],
        ),
    ]
