# Generated by Django 3.2.10 on 2022-02-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translator',
            options={'verbose_name': 'Video Translation', 'verbose_name_plural': 'Video Translations'},
        ),
        migrations.AddField(
            model_name='translator',
            name='current_task',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='translator',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('FAILED', 'FAILED'), ('COMPLETED', 'COMPLETED'), ('LOADING', 'LOADING')], default='PENDING', max_length=100),
        ),
    ]
